#!/bin/sh
# Guards the manual security hardening applied to .github/workflows/release.yml.
#
# release.yml carries a "This file was autogenerated by dist" header, and
# `dist generate` — which runs as part of routine dist config changes — rewrites
# it from cargo-dist's template, silently discarding every change below. Without
# this check that regression is invisible: the workflow keeps working, just
# without the hardening. If this script fails after a legitimate regeneration,
# re-apply the hardening rather than relaxing the check.

set -eu

WORKFLOW="${1:-.github/workflows/release.yml}"
FAIL=0

pass() { echo "  PASS: $1"; }
fail() { echo "  FAIL: $1"; FAIL=1; }

if [ ! -f "$WORKFLOW" ]; then
    echo "workflow not found: $WORKFLOW" >&2
    exit 1
fi

echo "==> Release workflow hardening"

# 1. Third-party actions must be pinned to a commit SHA. A mutable tag (@v6)
#    lets whoever controls the tag change what runs in a job holding our
#    publish tokens.
if grep -nE '^\s*(-\s*)?uses:\s*[^@]+@v[0-9]' "$WORKFLOW" >/dev/null 2>&1; then
    echo "    unpinned:"
    grep -nE '^\s*(-\s*)?uses:\s*[^@]+@v[0-9]' "$WORKFLOW" | sed 's/^/      /'
    fail "actions must be pinned to a 40-char commit SHA, not a mutable tag"
else
    pass "all actions pinned to commit SHAs"
fi

# 2. No pipe-to-shell installs: the fetched script is unauthenticated and
#    executes with the job's credentials.
if grep -nE 'curl[^|]*\|\s*(sh|bash)' "$WORKFLOW" >/dev/null 2>&1; then
    echo "    found:"
    grep -nE 'curl[^|]*\|\s*(sh|bash)' "$WORKFLOW" | sed 's/^/      /'
    fail "pipe-to-shell install reintroduced"
else
    pass "no pipe-to-shell installs"
fi

# 3. The rustup bootstrap must verify what it downloaded.
if grep -qF 'rustup-init' "$WORKFLOW"; then
    if grep -qF 'sha256sum -c -' "$WORKFLOW"; then
        pass "rustup-init download is checksum-verified"
    else
        fail "rustup-init is fetched without a checksum check"
    fi
else
    pass "no rustup-init bootstrap present"
fi

echo ""
if [ "$FAIL" -eq 0 ]; then
    echo "Release workflow hardening intact"
else
    echo "Release workflow hardening REGRESSED — see failures above" >&2
    exit 1
fi
